### PR TITLE
Fix: locked menus

### LINKED ISSUE #4: Inventory-start menu bug
Closing the inventory (i) with the Escape key triggers the start menu to open immediately. In addition to the start menu being unwantedly open, the player is able to move around the map still. When a start menu is open, everything in the game should be locked.

### PR DESCRIPTION
**Pull request by ChristianDalfonso**
Added a lock to the menu to prevent it from being open. Added check if lock to just return instead of proceeding further.

### CODE REVIEW

**Comment by adalfonso** [comment]
Nice job, that fixes it. Before I merge would you mind doing the following:

1) Invert the logic in `Game#lock` and `Game#unlock` to guard & short circuit; now that we're doing a couple things inside that `if` it's starting to get cramped. 

2) Format the changes with prettier. I think my prettier config is pretty standard. I really should add one to the project.

3) Update the version number to 0.20.1 in `package.json`

File: src/renderer/ts/Game.ts [hunk 1]
```diff
@@ -230,17 +230,15 @@ class Game implements Eventful, Drawable {
...
-        this.menu.lock();
-      }
+    if (this.state !== GameState.Play) {
+      return;
     }
+
+    this.state = state;
+    this.player.lock();
+
+    state !== GameState.Inventory ? this.inventory.lock() : null;
```
Comment (adalfonso) [inline src/renderer/ts/Game.ts]: @ChristianDalfonso please change these two lines back. While it's less code, it becomes harder to understand the intent of what its doing.

**Comment by adalfonso** [comment]
Thanks @ChristianDalfonso, I added one more comment. Please also squash these into a single commit before merge.

**Comment by adalfonso** [comment]
Looks good. Merging.
